[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./src/tests/keys/localnet/admin-bossj3JvwiNK7pvjr149DqdtJxf2gdygbcmEPTkb2F1.json"

[[test.genesis]]
address = "LbVRzDTvBDEcrthxfZ4RL6yiq3uZw8bS6MwtdY6UhFQ"
program = "./src/tests/artifacts/lb_clmm.so"

[[test.genesis]]
address = "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"
program = "./src/tests/artifacts/dynamic_amm.so"

[[test.genesis]]
address = "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"
program = "./src/tests/artifacts/dynamic_vault.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./src/tests/artifacts/metaplex.so"

[test.validator]
bind_address = "0.0.0.0"

[test]
startup_wait = 50000

[toolchain]
anchor_version = "0.28.0"
