name: Typescript SDK CI

on:
  pull_request:
    paths-ignore:
      - "config/**"
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
    branches:
      - main 

env:
  SOLANA_CLI_VERSION: 1.16.3
  NODE_VERSION: 18.14.2
  ANCHOR_CLI_VERSION: 0.28.0

jobs:
  sdk_changed_files:
    runs-on: ubuntu-latest
    outputs:
      sdk: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            src

  sdk_test:
    runs-on: ubuntu-latest
    needs: sdk_changed_files
    if: needs.sdk_changed_files.outputs.sdk == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: oven-sh/setup-bun@v2
      # This much more faster than anchor localnet
      - run: bun run start-test-validator & sleep 2
        shell: bash
      - run: bun install
        shell: bash
      - run: bun test
        shell: bash